version: "3.8"
services:
#   mosquitto:
#     image: eclipse-mosquitto
#     container_name: mqtt-broker
#     ports:
#       - "1883:1883"
#     volumes:
#       - ./backend/mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
  db:
      image: postgres:16
      restart: on-failure
      container_name: postgres-smp-db
      environment:
        POSTGRES_USER: postgres_local
        POSTGRES_PASSWORD: MyStrongPassw0rd!
        POSTGRES_DB: sm_parking
      ports:
        - "5432:5432"
      volumes:
        - ./ops/ps-init.sql:/docker-entrypoint-initdb.d/ps-init.sql
  smartparking-api:
    build:
      context: .
      dockerfile: SmartParking.Api/Dockerfile
    container_name: smartparking-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - APP_UID=1001
      - JwtSettings__Secret=MyVeryLongSecretKeyForJwtTokenGeneration12345678901234567890
      - JwtSettings__Issuer=SmartParking.Api
      - JwtSettings__Audience=SmartParking.Users
      - JwtSettings__ExpiryMinutes=60
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft=Warning
      - ConnectionStrings__Postgres=Host=host.docker.internal;Port=5432;Database=sm_parking;Username=postgres_local;Password=MyStrongPassw0rd!;Include Error Detail=true;